### ISSUE TITLE
Coupons triggers break Promotions details page

### ISSUE THREAD

**Issue by node82** [reactioncommerce/kinetic#155]
There is a promotion in the sample data that has an Action type of `Noop` 
this may just be the sample data, but wanted to call it out if `Noop` is an acceptable action type, viewing the promotion returns a white screen and a lot of console errors : listed below 
![image](https://user-images.githubusercontent.com/26560026/209251509-8c3b4f2f-0c47-467c-b916-440d5eaf0fe5.png)

```
Uncaught TypeError: Cannot read properties of undefined (reading 'all')
    at index.tsx:53:68
    at Array.map (<anonymous>)
    at formatTriggers (index.tsx:48:12)
    at PromotionDetails (index.tsx:130:43)
    at renderWithHooks (react-dom.development.js:16175:18)
    at updateFunctionComponent (react-dom.development.js:20387:20)
    at beginWork (react-dom.development.js:22430:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4161:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:16)
    at invokeGuardedCallback (react-dom.development.js:4274:31)
(anonymous) @ index.tsx:53
formatTriggers @ index.tsx:48
PromotionDetails @ index.tsx:130
renderWithHooks @ react-dom.development.js:16175
updateFunctionComponent @ react-dom.development.js:20387
beginWork @ react-dom.development.js:22430
callCallback2 @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
beginWork$1 @ react-dom.development.js:27405
performUnitOfWork @ react-dom.development.js:26513
workLoopSync @ react-dom.development.js:26422
renderRootSync @ react-dom.development.js:26390
performConcurrentWorkOnRoot @ react-dom.development.js:25694
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
index.tsx:53 
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'all')
    at index.tsx:53:68
    at Array.map (<anonymous>)
    at formatTriggers (index.tsx:48:12)
    at PromotionDetails (index.tsx:130:43)
    at renderWithHooks (react-dom.development.js:16175:18)
    at updateFunctionComponent (react-dom.development.js:20387:20)
    at beginWork (react-dom.development.js:22430:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4161:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4210:16)
    at invokeGuardedCallback (react-dom.development.js:4274:31)
(anonymous) @ index.tsx:53
formatTriggers @ index.tsx:48
PromotionDetails @ index.tsx:130
renderWithHooks @ react-dom.development.js:16175
updateFunctionComponent @ react-dom.development.js:20387
beginWork @ react-dom.development.js:22430
callCallback2 @ react-dom.development.js:4161
invokeGuardedCallbackDev @ react-dom.development.js:4210
invokeGuardedCallback @ react-dom.development.js:4274
beginWork$1 @ react-dom.development.js:27405
performUnitOfWork @ react-dom.development.js:26513
workLoopSync @ react-dom.development.js:26422
renderRootSync @ react-dom.development.js:26390
recoverFromConcurrentError @ react-dom.development.js:25806
performConcurrentWorkOnRoot @ react-dom.development.js:25706
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18572
```
```
 The above error occurred in the <PromotionDetails> component:

    at PromotionDetails (http://localhost:3003/src/pages/Promotions/Details/index.tsx:67:7)
    at PermissionGuard (http://localhost:3003/src/components/PermissionGuard/index.tsx:20:3)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at Outlet (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2601:26)
    at ErrorBoundary (http://localhost:3003/src/components/ErrorBoundary/ErrorBoundary.tsx:17:5)
    at ErrorBoundary (http://localhost:3003/src/components/ErrorBoundary/index.tsx:21:3)
    at main
    at http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:5593:50
    at Box3 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8333:19)
    at div
    at http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:5593:50
    at Box3 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8333:19)
    at AppLayout (http://localhost:3003/src/containers/Layouts/AppLayout.tsx:27:3)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at Outlet (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2601:26)
    at RequireShopRoute (http://localhost:3003/src/components/Routes/RequireShopRoute.tsx:23:7)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at Outlet (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2601:26)
    at RequireAuthRoute (http://localhost:3003/src/components/Routes/RequireAuthRoute.tsx:23:7)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at AccountProvider (http://localhost:3003/src/containers/AccountProvider/index.tsx:45:3)
    at ShopProvider (http://localhost:3003/src/containers/ShopProvider/index.tsx:34:3)
    at ToastProvider (http://localhost:3003/src/containers/ToastProvider/index.tsx:66:3)
    at Suspense
    at App (http://localhost:3003/src/App.tsx:26:24)
    at Router (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2608:15)
    at BrowserRouter (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2992:5)
    at QueryClientProvider2 (http://localhost:3003/node_modules/.vite/deps/react-query.js?v=1cd1f8fe:2663:21)
    at LocalizationProvider (http://localhost:3003/node_modules/.vite/deps/chunk-NT3ESHRI.js?v=1cd1f8fe:583:17)
    at InnerThemeProvider (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8272:17)
    at ThemeProvider2 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8021:5)
    at ThemeProvider3 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8280:5)
```
```
React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:18572
callback @ react-dom.development.js:18640
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23263
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects_begin @ react-dom.development.js:24546
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25848
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:22738 
```
```
Uncaught TypeError: Cannot use 'in' operator to search for 'errors' in undefined
    at formatErrorResponse (errorHandlers.ts:5:7)
    at ErrorBoundary.componentDidCatch (ErrorBoundary.tsx:32:22)
    at ErrorBoundary.callback (react-dom.development.js:18653:12)
    at callCallback (react-dom.development.js:13122:12)
    at commitUpdateQueue (react-dom.development.js:13143:9)
    at commitLayoutEffectOnFiber (react-dom.development.js:23263:13)
    at commitLayoutMountEffects_complete (react-dom.development.js:24578:9)
    at commitLayoutEffects_begin (react-dom.development.js:24564:7)
    at commitLayoutEffects_begin (react-dom.development.js:24546:11)
    at commitLayoutEffects (react-dom.development.js:24502:3)
formatErrorResponse @ errorHandlers.ts:5
componentDidCatch @ ErrorBoundary.tsx:32
callback @ react-dom.development.js:18653
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23263
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects_begin @ react-dom.development.js:24546
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25848
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:18572 
```
```
The above error occurred in the <ErrorBoundary> component:

    at ErrorBoundary (http://localhost:3003/src/components/ErrorBoundary/ErrorBoundary.tsx:17:5)
    at ErrorBoundary (http://localhost:3003/src/components/ErrorBoundary/index.tsx:21:3)
    at main
    at http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:5593:50
    at Box3 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8333:19)
    at div
    at http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:5593:50
    at Box3 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8333:19)
    at AppLayout (http://localhost:3003/src/containers/Layouts/AppLayout.tsx:27:3)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at Outlet (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2601:26)
    at RequireShopRoute (http://localhost:3003/src/components/Routes/RequireShopRoute.tsx:23:7)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at Outlet (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2601:26)
    at RequireAuthRoute (http://localhost:3003/src/components/Routes/RequireAuthRoute.tsx:23:7)
    at RenderedRoute (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2369:5)
    at AccountProvider (http://localhost:3003/src/containers/AccountProvider/index.tsx:45:3)
    at ShopProvider (http://localhost:3003/src/containers/ShopProvider/index.tsx:34:3)
    at ToastProvider (http://localhost:3003/src/containers/ToastProvider/index.tsx:66:3)
    at Suspense
    at App (http://localhost:3003/src/App.tsx:26:24)
    at Router (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2608:15)
    at BrowserRouter (http://localhost:3003/node_modules/.vite/deps/react-router-dom.js?v=1cd1f8fe:2992:5)
    at QueryClientProvider2 (http://localhost:3003/node_modules/.vite/deps/react-query.js?v=1cd1f8fe:2663:21)
    at LocalizationProvider (http://localhost:3003/node_modules/.vite/deps/chunk-NT3ESHRI.js?v=1cd1f8fe:583:17)
    at InnerThemeProvider (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8272:17)
    at ThemeProvider2 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8021:5)
    at ThemeProvider3 (http://localhost:3003/node_modules/.vite/deps/chunk-AUSQDR4S.js?v=1cd1f8fe:8280:5)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18572
update.callback @ react-dom.development.js:18605
callCallback @ react-dom.development.js:13122
commitUpdateQueue @ react-dom.development.js:13143
commitLayoutEffectOnFiber @ react-dom.development.js:23290
commitLayoutMountEffects_complete @ react-dom.development.js:24578
commitLayoutEffects_begin @ react-dom.development.js:24564
commitLayoutEffects @ react-dom.development.js:24502
commitRootImpl @ react-dom.development.js:26779
commitRoot @ react-dom.development.js:26638
performSyncWorkOnRoot @ react-dom.development.js:26073
flushSyncCallbacks @ react-dom.development.js:12009
commitRootImpl @ react-dom.development.js:26910
commitRoot @ react-dom.development.js:26638
finishConcurrentRender @ react-dom.development.js:25848
performConcurrentWorkOnRoot @ react-dom.development.js:25765
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
react-dom.development.js:12023 
```
```
Uncaught TypeError: Cannot use 'in' operator to search for 'errors' in undefined
    at formatErrorResponse (errorHandlers.ts:5:7)
    at ErrorBoundary.componentDidCatch (ErrorBoundary.tsx:32:22)
    at ErrorBoundary.callback (react-dom.development.js:18653:12)
    at callCallback (react-dom.development.js:13122:12)
    at commitUpdateQueue (react-dom.development.js:13143:9)
    at commitLayoutEffectOnFiber (react-dom.development.js:23263:13)
    at commitLayoutMountEffects_complete (react-dom.development.js:24578:9)
    at commitLayoutEffects_begin (react-dom.development.js:24564:7)
    at commitLayoutEffects_begin (react-dom.development.js:24546:11)
    at commitLayoutEffects (react-dom.development.js:24502:3)
```

**Comment by vannguyenn** [comment]
This issue happens because the trigger is a `coupons` trigger, which we currently do not support yet.
